services:
  backend:
    image: plone/plone-backend:6.0
    restart: always
    environment:
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRESS_DB: plone
    ports:
      - "5432:5432"
