services:
  backend:
    image: plone/plone-backend:6.0
    ports:
      - '8080:8080'
    environment:
      - SITE=site 
      - 'ADDONS=plone.restapi==8.21.0 plone.volto==4.0.0a3 plone.rest==2.0.0a2 plone.app.iterate==4.0.2'
      - 'PROFILES=plone.volto:default-homepage'


  frontend:
    image: plone/plone-frontend:latest
    ports:
      - '3000:3000'
    restart: always
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/site 
      RAZZLE_DEV_PROXY_API_PATH: http://backend:8080/site 
    depends_on:
      - backend
